"""Valores comuns do jogo e padrões reservados para a futura rede do EP."""

BOARD_ROWS = 20
BOARD_COLUMNS = 10
MIN_CELL = 0
MAX_CELL = 8
ATTACK_QUANTITIES = frozenset({1, 2, 4})
NICKNAME_PATTERN = r"[A-Za-z0-9_]{1,20}"
KO_CAUSES = frozenset({"SPAWN", "OVERFLOW"})

HELLO_TIMEOUT_SECONDS = 5
KEEPALIVE_INTERVAL_SECONDS = 5
INACTIVITY_TIMEOUT_SECONDS = 15
FINAL_DRAIN_SECONDS = 1
MAX_MESSAGE_BYTES = 512
MAX_OUTPUT_BYTES = 4096
